### ISSUE TITLE
The check-drbd-status.sh does not support multiple volumes

### ISSUE THREAD

**Issue by louismunro** [inverse-inc/packetfence-monitoring-scripts#1]
It will fail when there are multiple DRBD volumes, and will succeed erroneously if only one of the multiple volumes succeed.

This is not an academic concern.
I have that configuration running for some clients.

**Comment by julsemaan** [comment]
We don't actively support DRBD anyway, so this can be closed.

Even less support for people with exotic DRBD configuration
