### ISSUE TITLE
Currently-at has been removed, need to remove the script.

### ISSUE THREAD

**Issue by fdurand** [inverse-inc/packetfence-monitoring-scripts#33]
SInce https://github.com/inverse-inc/packetfence/pull/5121 the file currently-at has been removed, so the monitoring scripts need to be adapted.

**Comment by nqb** [comment]
Thanks @fdurand, I missed this part.

**Comment by nqb** [comment]
@julsemaan and @fdurand,

From my understanding, if I delete `check-currently-at.sh` script, our registry will be updated and all users that run with a version prior to devel will have this check automagically deleted from their monit configuration.

My proposal is to rename  `check-currently-at.sh` to `check-configurator-disabled.sh` and to handle both cases in one script that work on current and future setups.

Let me know if it's fine for you.

**Comment by julsemaan** [comment]
From what I can tell the script deletion isn't being handled.

What we should do is scope the old script to versions 10 and below

And then scope the new script to versions 10 and above

**Comment by nqb** [comment]
@julsemaan, I don't see code in #34 in http://inverse.ca/downloads/PacketFence/monitoring-scripts/v1/scripts/check-currently-at.sh. Merge has been done almost one hour ago, is there is something to trigger on our side ?

**Comment by julsemaan** [comment]
Done
